name: NSW Live Traffic Archiver
on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'
jobs:
  archive:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Run script
      run: node index.js
      timeout-minutes: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TFNSW_API_KEY: ${{ secrets.TFNSW_API_KEY }}
